# Copyright (c) 2026, Neotec Integrated Solutions
"""
Additional plan templates covering the frameworks this app assesses against.

Same row shape as plans.py: (wbs, title, duration_days, responsible_role,
phase, depends_on). Durations are working days; 0 marks a milestone or a
phase header. Every plan follows the same five-stage spine — mobilise, assess,
build, implement, assure — because that is what makes them comparable when a
client runs two programmes at once.
"""

EXTRA_TEMPLATES = [
	{
		"name": "SDAIA PDPL Privacy Programme",
		"framework": "SDAIA PDPL",
		"engagement_type": "Managed Compliance (ongoing)",
		"source": "Saudi Personal Data Protection Law and its Implementing Regulations",
		"description": "Privacy programme from data discovery to registered, defensible processing.",
		"tasks": [
			("1.0", "Mobilisation", 0, "Project Manager", "Mobilisation", ""),
			("1.1", "Kick-off, scope and entity roles (controller / processor)", 3, "Project Manager", "Mobilisation", ""),
			("1.2", "Appoint the Data Protection Officer", 5, "Legal", "Mobilisation", ""),
			("2.0", "Discovery", 0, "", "Discovery", ""),
			("2.1", "Personal data inventory and data mapping", 15, "GRC Consultant", "Discovery", ""),
			("2.2", "Record of processing activities (RoPA)", 10, "GRC Consultant", "Discovery", ""),
			("2.3", "Lawful basis and consent review per activity", 8, "Legal", "Discovery", ""),
			("2.4", "Cross-border transfer inventory and risk review", 6, "Legal", "Discovery", ""),
			("3.0", "Build", 0, "", "Build", ""),
			("3.1", "Personal data protection policy and standards", 10, "GRC Consultant", "Build", ""),
			("3.2", "Privacy notices and consent mechanics", 8, "Legal", "Build", ""),
			("3.3", "Data subject rights procedure and intake channel", 8, "GRC Consultant", "Build", ""),
			("3.4", "Retention schedule and disposal procedure", 8, "GRC Consultant", "Build", ""),
			("3.5", "Breach notification procedure (72-hour path)", 6, "CISO", "Build", ""),
			("3.6", "Processor contracts and data processing agreements", 10, "Legal", "Build", ""),
			("4.0", "Implementation", 0, "", "Implementation", ""),
			("4.1", "DPIA methodology and first assessments", 10, "GRC Consultant", "Implementation", ""),
			("4.2", "Technical controls: minimisation, encryption, access", 12, "IT Manager", "Implementation", ""),
			("4.3", "Privacy awareness training", 5, "HR", "Implementation", ""),
			("5.0", "Assurance", 0, "", "Assurance", ""),
			("5.1", "Rights-request and breach drill", 4, "GRC Consultant", "Assurance", ""),
			("5.2", "Internal privacy audit", 8, "Internal Audit", "Assurance", ""),
			("5.3", "SDAIA registration and residual gap acceptance", 5, "Legal", "Assurance", ""),
			("5.4", "PDPL programme operational", 0, "Legal", "Closure", ""),
		],
	},
	{
		"name": "ISO 22301 Business Continuity (BCMS)",
		"framework": "ISO 22301",
		"engagement_type": "Managed Compliance (ongoing)",
		"source": "ISO 22301:2019 clauses 4-10",
		"description": "BCMS build through BIA and strategy to a tested, certifiable programme.",
		"tasks": [
			("1.0", "Mobilisation", 0, "Project Manager", "Mobilisation", ""),
			("1.1", "Kick-off and BCMS scope (4.3)", 4, "Project Manager", "Mobilisation", ""),
			("1.2", "Leadership commitment and BC policy (5.2)", 6, "Business Owner", "Mobilisation", ""),
			("2.0", "Analysis", 0, "", "Analysis", ""),
			("2.1", "Business impact analysis (8.2.2)", 15, "GRC Consultant", "Analysis", ""),
			("2.2", "Risk assessment for disruption (8.2.3)", 8, "GRC Consultant", "Analysis", ""),
			("2.3", "Set RTO, RPO and MBCO per process", 5, "Business Owner", "Analysis", ""),
			("3.0", "Strategy", 0, "", "Strategy", ""),
			("3.1", "Continuity strategy selection (8.3)", 10, "GRC Consultant", "Strategy", ""),
			("3.2", "Resource requirements and gap costing", 6, "IT Manager", "Strategy", ""),
			("4.0", "Implementation", 0, "", "Implementation", ""),
			("4.1", "Business continuity plans per critical process (8.4)", 15, "GRC Consultant", "Implementation", ""),
			("4.2", "ICT disaster recovery plans", 12, "IT Manager", "Implementation", ""),
			("4.3", "Incident response structure and call tree", 6, "CISO", "Implementation", ""),
			("4.4", "Awareness and role-based BC training (7.2)", 6, "HR", "Implementation", ""),
			("5.0", "Validation", 0, "", "Validation", ""),
			("5.1", "Tabletop exercise", 4, "GRC Consultant", "Validation", ""),
			("5.2", "Full failover / recovery test (8.5)", 6, "IT Manager", "Validation", ""),
			("5.3", "Exercise report and plan updates", 5, "GRC Consultant", "Validation", ""),
			("5.4", "Internal audit (9.2)", 8, "Internal Audit", "Validation", ""),
			("5.5", "Management review (9.3)", 3, "Business Owner", "Validation", ""),
			("5.6", "Certification ready", 0, "Project Manager", "Closure", ""),
		],
	},
	{
		"name": "PCI DSS v4.0 Compliance",
		"framework": "PCI DSS",
		"engagement_type": "Managed Compliance (ongoing)",
		"source": "PCI DSS v4.0, 12 requirements",
		"description": "Scoping through remediation to ROC/SAQ readiness for a cardholder data environment.",
		"tasks": [
			("1.0", "Scoping", 0, "Project Manager", "Scoping", ""),
			("1.1", "Kick-off and merchant / service provider level confirmation", 3, "Project Manager", "Scoping", ""),
			("1.2", "Cardholder data discovery and flow mapping", 12, "GRC Consultant", "Scoping", ""),
			("1.3", "CDE scope definition and segmentation review", 8, "IT Manager", "Scoping", ""),
			("2.0", "Gap Assessment", 0, "", "Assessment", ""),
			("2.1", "Gap assessment against the 12 requirements", 15, "GRC Consultant", "Assessment", ""),
			("2.2", "Remediation plan and ownership", 5, "Project Manager", "Assessment", ""),
			("3.0", "Remediation", 0, "", "Remediation", ""),
			("3.1", "Req 1-2: network security controls and secure configuration", 12, "IT Manager", "Remediation", ""),
			("3.2", "Req 3-4: stored data protection and transmission encryption", 12, "IT Manager", "Remediation", ""),
			("3.3", "Req 5-6: malware defence and secure development", 10, "IT Manager", "Remediation", ""),
			("3.4", "Req 7-9: access control and physical access", 12, "IT Manager", "Remediation", ""),
			("3.5", "Req 10-11: logging, monitoring and testing", 12, "CISO", "Remediation", ""),
			("3.6", "Req 12: policy, awareness and third-party management", 10, "GRC Consultant", "Remediation", ""),
			("4.0", "Validation", 0, "", "Validation", ""),
			("4.1", "Internal and external vulnerability scans (ASV)", 8, "External Auditor", "Validation", ""),
			("4.2", "Penetration test and segmentation test", 10, "External Auditor", "Validation", ""),
			("4.3", "Evidence pack assembly", 8, "GRC Consultant", "Validation", ""),
			("4.4", "QSA assessment / SAQ completion", 10, "External Auditor", "Validation", ""),
			("4.5", "Attestation of compliance signed", 0, "CISO", "Closure", ""),
		],
	},
	{
		"name": "NIST CSF 2.0 Programme",
		"framework": "NIST CSF 2.0",
		"engagement_type": "Managed Compliance (ongoing)",
		"source": "NIST Cybersecurity Framework 2.0 — GOVERN, IDENTIFY, PROTECT, DETECT, RESPOND, RECOVER",
		"description": "Current and target profile across all six functions, with a prioritised action plan.",
		"tasks": [
			("1.0", "Mobilisation", 0, "Project Manager", "Mobilisation", ""),
			("1.1", "Kick-off and organisational profile scope", 3, "Project Manager", "Mobilisation", ""),
			("1.2", "Define target profile and risk tolerance", 6, "CISO", "Mobilisation", ""),
			("2.0", "Current Profile", 0, "", "Assessment", ""),
			("2.1", "GOVERN: strategy, roles, policy, oversight, supply chain", 10, "CISO", "Assessment", ""),
			("2.2", "IDENTIFY: asset, risk and improvement management", 10, "GRC Consultant", "Assessment", ""),
			("2.3", "PROTECT: identity, awareness, data, platform, resilience", 12, "IT Manager", "Assessment", ""),
			("2.4", "DETECT: continuous monitoring and adverse event analysis", 8, "CISO", "Assessment", ""),
			("2.5", "RESPOND: incident management, analysis, mitigation", 8, "CISO", "Assessment", ""),
			("2.6", "RECOVER: recovery plan execution and communication", 6, "IT Manager", "Assessment", ""),
			("3.0", "Analysis", 0, "", "Analysis", ""),
			("3.1", "Current vs target profile gap analysis", 8, "GRC Consultant", "Analysis", ""),
			("3.2", "Prioritised action plan with tiers", 6, "GRC Consultant", "Analysis", ""),
			("4.0", "Implementation", 0, "", "Implementation", ""),
			("4.1", "Execute priority-one actions", 25, "IT Manager", "Implementation", ""),
			("4.2", "Execute priority-two actions", 20, "IT Manager", "Implementation", ""),
			("5.0", "Assurance", 0, "", "Assurance", ""),
			("5.1", "Re-assess and update the current profile", 10, "GRC Consultant", "Assurance", ""),
			("5.2", "Executive reporting pack", 4, "CISO", "Assurance", ""),
			("5.3", "Target profile achieved", 0, "CISO", "Closure", ""),
		],
	},
	{
		"name": "ISO 42001 AI Management System",
		"framework": "ISO 42001",
		"engagement_type": "ISO 42001 AI Governance",
		"source": "ISO/IEC 42001:2023 clauses 4-10 and Annex A",
		"description": "AIMS build covering AI inventory, impact assessment and lifecycle controls.",
		"tasks": [
			("1.0", "Mobilisation", 0, "Project Manager", "Mobilisation", ""),
			("1.1", "Kick-off and AIMS scope (4.3)", 4, "Project Manager", "Mobilisation", ""),
			("1.2", "AI policy and leadership commitment (5.2)", 6, "Business Owner", "Mobilisation", ""),
			("2.0", "Discovery", 0, "", "Discovery", ""),
			("2.1", "AI system inventory and role classification", 10, "GRC Consultant", "Discovery", ""),
			("2.2", "AI risk assessment (6.1.2)", 10, "GRC Consultant", "Discovery", ""),
			("2.3", "AI system impact assessment (6.1.4)", 10, "GRC Consultant", "Discovery", ""),
			("3.0", "Build", 0, "", "Build", ""),
			("3.1", "Statement of Applicability against Annex A", 8, "GRC Consultant", "Build", ""),
			("3.2", "AI lifecycle and development controls", 12, "IT Manager", "Build", ""),
			("3.3", "Data governance for AI training and operation", 10, "IT Manager", "Build", ""),
			("3.4", "Transparency, human oversight and incident handling", 8, "CISO", "Build", ""),
			("3.5", "Third-party and supplier AI requirements", 6, "Legal", "Build", ""),
			("4.0", "Assurance", 0, "", "Assurance", ""),
			("4.1", "Awareness and competence (7.2, 7.3)", 5, "HR", "Assurance", ""),
			("4.2", "Internal audit (9.2)", 8, "Internal Audit", "Assurance", ""),
			("4.3", "Management review (9.3)", 3, "Business Owner", "Assurance", ""),
			("4.4", "Certification ready", 0, "Project Manager", "Closure", ""),
		],
	},
	{
		"name": "Aramco SACS-002 Third Party Certification",
		"framework": "Aramco SACS-002",
		"engagement_type": "Aramco CCC Pursuit",
		"source": "Saudi Aramco Third Party Cybersecurity Standard SACS-002",
		"description": "CCC certification track for a supplier connecting to or serving Saudi Aramco.",
		"tasks": [
			("1.0", "Mobilisation", 0, "Project Manager", "Mobilisation", ""),
			("1.1", "Kick-off and applicable branch determination (CCC / SCC / CIS)", 4, "Project Manager", "Mobilisation", ""),
			("1.2", "Registration and portal onboarding", 4, "Project Manager", "Mobilisation", ""),
			("2.0", "Assessment", 0, "", "Assessment", ""),
			("2.1", "Self-assessment against the applicable control set", 12, "GRC Consultant", "Assessment", ""),
			("2.2", "Gap report and remediation plan", 5, "GRC Consultant", "Assessment", ""),
			("3.0", "Remediation", 0, "", "Remediation", ""),
			("3.1", "Governance and policy remediation", 10, "CISO", "Remediation", ""),
			("3.2", "Technical control remediation", 20, "IT Manager", "Remediation", ""),
			("3.3", "Third-party and supply-chain remediation", 8, "Legal", "Remediation", ""),
			("4.0", "Certification", 0, "", "Certification", ""),
			("4.1", "Evidence pack assembly", 10, "GRC Consultant", "Certification", ""),
			("4.2", "Accredited assessor audit", 10, "External Auditor", "Certification", ""),
			("4.3", "Non-conformity closure", 10, "IT Manager", "Certification", ""),
			("4.4", "Certificate issued", 0, "Project Manager", "Closure", ""),
		],
	},
	{
		"name": "Cybersecurity Gap Assessment (Short Engagement)",
		"framework": "General",
		"engagement_type": "Custom",
		"source": "Neotec delivery methodology",
		"description": "Four to six week diagnostic against any framework, ending in a costed roadmap.",
		"tasks": [
			("1.0", "Initiation", 0, "Project Manager", "Initiation", ""),
			("1.1", "Kick-off, scope and stakeholder map", 2, "Project Manager", "Initiation", ""),
			("1.2", "Document request list issued", 1, "GRC Consultant", "Initiation", ""),
			("2.0", "Fieldwork", 0, "", "Fieldwork", ""),
			("2.1", "Document review", 5, "GRC Consultant", "Fieldwork", ""),
			("2.2", "Stakeholder interviews", 5, "GRC Consultant", "Fieldwork", ""),
			("2.3", "Technical walkthroughs and sampling", 5, "GRC Consultant", "Fieldwork", ""),
			("3.0", "Analysis", 0, "", "Analysis", ""),
			("3.1", "Control scoring and gap identification", 5, "GRC Consultant", "Analysis", ""),
			("3.2", "Risk-rank the gaps", 3, "GRC Consultant", "Analysis", ""),
			("3.3", "Remediation roadmap with effort and cost", 4, "Project Manager", "Analysis", ""),
			("4.0", "Reporting", 0, "", "Reporting", ""),
			("4.1", "Draft report and internal QA", 4, "Project Manager", "Reporting", ""),
			("4.2", "Client walkthrough and feedback", 2, "Project Manager", "Reporting", ""),
			("4.3", "Final report issued", 2, "Project Manager", "Reporting", ""),
			("4.4", "Engagement closed", 0, "Project Manager", "Closure", ""),
		],
	},
	{
		"name": "Internal Audit Engagement",
		"framework": "General",
		"engagement_type": "Custom",
		"source": "IIA International Professional Practices Framework",
		"description": "Risk-based internal audit from planning to follow-up on agreed actions.",
		"tasks": [
			("1.0", "Planning", 0, "Internal Audit", "Planning", ""),
			("1.1", "Audit scope, objectives and criteria", 3, "Internal Audit", "Planning", ""),
			("1.2", "Risk assessment and audit programme", 4, "Internal Audit", "Planning", ""),
			("1.3", "Opening meeting", 1, "Internal Audit", "Planning", ""),
			("2.0", "Fieldwork", 0, "", "Fieldwork", ""),
			("2.1", "Walkthroughs and control design testing", 6, "Internal Audit", "Fieldwork", ""),
			("2.2", "Operating effectiveness testing and sampling", 8, "Internal Audit", "Fieldwork", ""),
			("2.3", "Working papers and evidence indexing", 4, "Internal Audit", "Fieldwork", ""),
			("3.0", "Reporting", 0, "", "Reporting", ""),
			("3.1", "Draft findings and management responses", 5, "Internal Audit", "Reporting", ""),
			("3.2", "Closing meeting", 1, "Internal Audit", "Reporting", ""),
			("3.3", "Final audit report issued", 3, "Internal Audit", "Reporting", ""),
			("4.0", "Follow-up", 0, "", "Follow-up", ""),
			("4.1", "Track remediation of agreed actions", 10, "Internal Audit", "Follow-up", ""),
			("4.2", "Follow-up audit and closure", 5, "Internal Audit", "Follow-up", ""),
			("4.3", "Audit closed", 0, "Internal Audit", "Closure", ""),
		],
	},
	{
		"name": "Cybersecurity Policy Framework Development",
		"framework": "General",
		"engagement_type": "Custom",
		"source": "Neotec delivery methodology + policy library",
		"description": "Draft, review, approve and publish a full policy set from the global library.",
		"tasks": [
			("1.0", "Scoping", 0, "Project Manager", "Scoping", ""),
			("1.1", "Confirm applicable frameworks and policy set", 3, "GRC Consultant", "Scoping", ""),
			("1.2", "Adopt baseline policies from the global library", 2, "GRC Consultant", "Scoping", ""),
			("1.3", "Assign policy owners", 2, "CISO", "Scoping", ""),
			("2.0", "Drafting", 0, "", "Drafting", ""),
			("2.1", "Draft governance and organisational policies", 10, "GRC Consultant", "Drafting", ""),
			("2.2", "Draft technical and operational policies", 15, "GRC Consultant", "Drafting", ""),
			("2.3", "Draft privacy and third-party policies", 8, "GRC Consultant", "Drafting", ""),
			("3.0", "Review and Approval", 0, "", "Approval", ""),
			("3.1", "Owner review cycle", 8, "Business Owner", "Approval", ""),
			("3.2", "Legal and compliance review", 5, "Legal", "Approval", ""),
			("3.3", "Committee approval", 3, "CISO", "Approval", ""),
			("3.4", "Board endorsement", 3, "Business Owner", "Approval", ""),
			("4.0", "Publication", 0, "", "Publication", ""),
			("4.1", "Publish and communicate", 4, "GRC Consultant", "Publication", ""),
			("4.2", "Collect employee acknowledgements", 8, "HR", "Publication", ""),
			("4.3", "Policy set live", 0, "CISO", "Closure", ""),
		],
	},
	{
		"name": "Third Party Risk Management Programme",
		"framework": "General",
		"engagement_type": "Custom",
		"source": "ISO 27001 A.5.19-A.5.23, SAMA CSF 3.4, NCA ECC domain 4",
		"description": "Stand up vendor risk management from inventory to continuous monitoring.",
		"tasks": [
			("1.0", "Foundation", 0, "Project Manager", "Foundation", ""),
			("1.1", "Vendor inventory and criticality tiering", 10, "Procurement Manager".replace("Procurement Manager", "Business Owner"), "Foundation", ""),
			("1.2", "Third-party risk policy and standard", 8, "GRC Consultant", "Foundation", ""),
			("1.3", "Due diligence questionnaire set by tier", 6, "GRC Consultant", "Foundation", ""),
			("2.0", "Assessment", 0, "", "Assessment", ""),
			("2.1", "Assess tier-one critical vendors", 15, "GRC Consultant", "Assessment", ""),
			("2.2", "Assess tier-two vendors", 12, "GRC Consultant", "Assessment", ""),
			("2.3", "Risk-rate and record findings", 5, "GRC Consultant", "Assessment", ""),
			("3.0", "Contracting", 0, "", "Contracting", ""),
			("3.1", "Security clauses, right to audit and exit terms", 10, "Legal", "Contracting", ""),
			("3.2", "Remediation agreements with high-risk vendors", 10, "Legal", "Contracting", ""),
			("4.0", "Monitoring", 0, "", "Monitoring", ""),
			("4.1", "SLA and security reporting cadence", 5, "Business Owner", "Monitoring", ""),
			("4.2", "Reassessment calendar and KPI reporting", 5, "GRC Consultant", "Monitoring", ""),
			("4.3", "Programme operational", 0, "CISO", "Closure", ""),
		],
	},
	{
		"name": "Incident Response Readiness",
		"framework": "General",
		"engagement_type": "Custom",
		"source": "NIST SP 800-61r2, SAMA CSF 3.3.15, NCA ECC 2-13",
		"description": "Build and prove an incident response capability, including regulator notification paths.",
		"tasks": [
			("1.0", "Assessment", 0, "Project Manager", "Assessment", ""),
			("1.1", "Current capability review", 5, "CISO", "Assessment", ""),
			("1.2", "Scenario and threat profile definition", 4, "CISO", "Assessment", ""),
			("2.0", "Build", 0, "", "Build", ""),
			("2.1", "Incident response plan and classification scheme", 10, "CISO", "Build", ""),
			("2.2", "Playbooks for priority scenarios", 12, "CISO", "Build", ""),
			("2.3", "Regulator notification paths and templates", 5, "GRC Consultant", "Build", ""),
			("2.4", "Crisis communication and media protocol", 5, "Legal", "Build", ""),
			("2.5", "Forensic readiness and evidence handling", 6, "IT Manager", "Build", ""),
			("3.0", "Enablement", 0, "", "Enablement", ""),
			("3.1", "Responder training", 5, "HR", "Enablement", ""),
			("3.2", "On-call roster and escalation matrix", 3, "CISO", "Enablement", ""),
			("4.0", "Validation", 0, "", "Validation", ""),
			("4.1", "Tabletop exercise", 3, "CISO", "Validation", ""),
			("4.2", "Simulated incident with regulator notification drill", 4, "CISO", "Validation", ""),
			("4.3", "Lessons learned and plan update", 4, "CISO", "Validation", ""),
			("4.4", "Capability proven", 0, "CISO", "Closure", ""),
		],
	},
	{
		"name": "Certification Surveillance and Recertification",
		"framework": "General",
		"engagement_type": "Custom",
		"source": "ISO/IEC 17021 certification cycle",
		"description": "Annual surveillance or three-year recertification cycle for an existing certified system.",
		"tasks": [
			("1.0", "Preparation", 0, "Project Manager", "Preparation", ""),
			("1.1", "Confirm audit date and scope changes", 2, "Project Manager", "Preparation", ""),
			("1.2", "Review changes since the last audit", 4, "GRC Consultant", "Preparation", ""),
			("1.3", "Close open non-conformities and observations", 10, "GRC Consultant", "Preparation", ""),
			("2.0", "Internal Assurance", 0, "", "Assurance", ""),
			("2.1", "Internal audit cycle", 8, "Internal Audit", "Assurance", ""),
			("2.2", "Management review", 3, "Business Owner", "Assurance", ""),
			("2.3", "Risk assessment and SoA refresh", 6, "GRC Consultant", "Assurance", ""),
			("3.0", "External Audit", 0, "", "External Audit", ""),
			("3.1", "Evidence pack assembly", 6, "GRC Consultant", "External Audit", ""),
			("3.2", "Certification body audit", 4, "External Auditor", "External Audit", ""),
			("3.3", "Non-conformity response and closure", 10, "GRC Consultant", "External Audit", ""),
			("3.4", "Certificate maintained", 0, "Project Manager", "Closure", ""),
		],
	},
]
